#!/bin/bash
kills=`docker kill $(docker ps -q)`
mongo=`docker run -d --network=reddit --network-alias=post_db --network-alias=comment_db -v reddit_db:/data/db mongo:latest`
post=`docker run -d --network=reddit --network-alias=post verty/post:1.0`
comment=`docker run -d --network=reddit --network-alias=comment verty/comment:1.0`
ui=`docker run -d --network=reddit -p 9292:9292 verty/ui:1.0`
stat=`docker ps -q`
echo "----------------"
printf "Kill  running  docker containers\n$kills\n"
echo "----------------"
printf "Start docker container\n$stat\n"
echo "----------------"
